version: '3'

services:
  database:
    image: mariadb:10.5
    container_name: pterodactyl_database
    restart: always
    networks:
      - mcnet
    volumes:
      - /var/pterodactyl/panel/var/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=panel
      - MYSQL_USER=peter
      - MYSQL_PASSWORD=peter
  
  cache:
    image: redis:alpine
    container_name: pterodactyl_cache
    restart: always
    networks:
      - mcnet

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl_panel
    restart: always
    networks:
      - mcnet
    ports:
      - "80:80"
    links:
      - database
      - cache
    volumes:
      - /var/pterodactyl/panel/var/logs:/app/storage/logs
      - /var/pterodactyl/panel/var/files:/app/storage/app
    environment:
      # Local development setup - use your computer's local IP or hostname
      - APP_URL=http://192.168.0.23
      - APP_ENV=production
      - APP_KEY=base64:Q6HXRHadNmWPmFsJP3SC7hI0kg/pApK93OdVO5w83dg=
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=panel
      - DB_USERNAME=peter
      - DB_PASSWORD=peter
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=cache
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      # Using log driver instead of SMTP for local development
      - MAIL_DRIVER=log
      # No need to configure these for log driver
      # - MAIL_HOST=mail.example.com
      # - MAIL_PORT=587
      # - MAIL_USERNAME=no-reply@example.com
      # - MAIL_PASSWORD=password
      # - MAIL_ENCRYPTION=tls
      # - MAIL_FROM=no-reply@example.com
      # - MAIL_FROM_NAME="Pterodactyl Panel"

networks:
  mcnet:
    external: true
