version: '3'

services:
  wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl_wings
    restart: always
    networks:
      - mcnet
    ports:
      - "8080:8080"
      - "2022:2022"
    tty: true
    environment:
      - TZ=UTC
    volumes:
      - /var/pterodactyl/wings/config:/etc/pterodactyl
      - /var/pterodactyl/wings/data:/var/lib/pterodactyl
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/pterodactyl:/tmp/pterodactyl

networks:
  mcnet:
    external: true
